# Generated by Django 3.2.16 on 2023-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_text_comment_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='txt',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
