# Generated by Django 3.2.16 on 2023-12-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='txt',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='blog.location', verbose_name='Местоположение'),
        ),
    ]
